version: "3.2"
services:
  traefik:
    image: traefik:v2.5
    container_name: traefik-qr-v1
    command:
      # - "--log.level=DEBUG"
      - "--api=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      #test server
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=abrochu@lachapelle.me"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - default
    secrets:
      - htpasswd
    labels:
      - "traefik.enable=true"
      # To access dashbaord, trailing / is MANDATORY. dashboard/
      #- "traefik.http.routers.dashboard.rule=Host(`panel.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      #- "traefik.http.routers.dashboard.entrypoints=websecure"
      #- "traefik.http.routers.dashboard.service=api@internal"
      #- "traefik.http.routers.dashboard.tls=true"
      #- "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      # Dashboard. TODO: use custom subdomain. TODO: use proper login.
      #- "traefik.http.middlewares.authtraefik.basicauth.usersfile=/run/secrets/htpasswd"
      #- "traefik.http.routers.dashboard.middlewares=authtraefik"

      # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  php-dynamic-qrcode:
    image: "giandonatoinverso/php-dynamic-qr-code:latest"
    #build: .
    restart: "unless-stopped"
    environment:
      TYPE: "docker"
      QRCODE_GENERATOR: "internal-chillerlan.qrcode"
      BASE_URL: "https://url.com"
      DATABASE_HOST: "php-dynamic-qrcode-db"
      DATABASE_PORT: "3306"
      DATABASE_NAME: "qrcode"
      DATABASE_USER: "qrcode"
      DATABASE_PASSWORD: "changeme"
      DATABASE_PREFIX: ""
      DATABASE_CHARSET: "utf8"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.infra-qr.rule=Host(`qr.localhost`)"
      - "traefik.http.routers.infra-qr.entrypoints=websecure"
      - "traefik.http.routers.infra-qr.tls.certresolver=myresolver"
      - "traefik.http.routers.infra-qr.tls=true"
    depends_on:
      - php-dynamic-qrcode-db
    volumes:
      - php_dynamic_qrcode_saved_qrcode_data:/var/www/html/saved_qrcode
    networks:
      - php-dynamic-qrcode-network
      - default

  php-dynamic-qrcode-db:
    # image: "giandonatoinverso/php-dynamic-qr-code-db:latest"
    build: .
    restart: "unless-stopped"
    volumes:
      - php_dynamic_qrcode_db_data:/var/lib/mysql
    secrets:
       - db_root_password
       - db_password
    ports:
      - '13306:3306'
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: "qrcode"
      MYSQL_USER: "qrcode"
    networks:
      - php-dynamic-qrcode-network

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #       - 8080:8080
  #   networks:
  #     - php-dynamic-qrcode-network

volumes:
  php_dynamic_qrcode_db_data:
  php_dynamic_qrcode_saved_qrcode_data:

networks:
  php-dynamic-qrcode-network:
    driver: bridge
  default:
      external:
          name: gateway

secrets:
  htpasswd:
    file: ./secrets/passwords.txt
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt